### ISSUE TITLE
Question/R&D: Disqus

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#126]
### Descriptive summary

Decision needed as to whether we migrate Disqus commenting functionality to DAMS5/horton.

### Rationale

It doesn't seem that, in the several years DAMS4 has been in production, it's a feature we've utilized. And it brings an additional 3rd-party dependency for each collection/object page load. 

That said, if we do still find that feature valuable, should we also use this opportunity to consider alternatives?

### Expected behavior

?

### Actual behavior

At the moment, this feature has not been migrated.

**Comment by gamontoya** [comment]
https://lisn.ucsd.edu/display/dlpg/2017-09-26+-+DLPG+Minutes

**Comment by gamontoya** [comment]
Revisit in the future.
