### ISSUE TITLE
Review and update the Chinese locale file in the Samvera repository

### ISSUE THREAD

**Issue by hweng** [ucsdlib/horton#132]
### Descriptive summary

 Review and update the Chinese locale file in the Samvera repository.

**Comment by hweng** [comment]
@mcritchlow Here is the instruction, feel free to update it: https://github.com/ucsdlib/horton/wiki/The-review-workflow-for-comparing-the-Chinese-translation-of-samvera-hyrax-locales-file

Here is the screenshot for new added/removed lines and their line number for hyax.zh.yml file from Apr. 14th to Aug. 23rd:
![screen shot 2017-08-29 at 3 39 53 pm](https://user-images.githubusercontent.com/2432753/29895408-da130f2c-8d8d-11e7-9775-f8b0479f3ab9.png)

**Comment by mcritchlow** [comment]
That looks great 👍  The only thing off the top I think might be valuable would be to add is a link in your example for Step 3 so people could be taken directly to an example.

**Comment by hweng** [comment]
Good point, @mcritchlow.  I've added the URL for step 2 because the step 3 and step 2 are the same url. In step 3 there is the instruction for searching and clicking the tabs which are the UI activities. 

If it looks good to you, would you send the link to them and can we talk about to move to the next step? Thanks!

**Comment by mcritchlow** [comment]
I think this is a great start. Whoever ends up being responsible for working with us on this will find this very valuable. I'm going to go ahead and close this. And once I get more direction on who to send this to, I'll do that. At the moment, it's unclear and I don't want to further confuse things :)
