### ISSUE TITLE
Upgrade to latest hyrax

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#135]
### Descriptive summary

- Please update to the latest Hyrax commit.
- Please provide a summary of the changes in the PR so the entire team understands the context of the changes.

Hyrax 2 beta1 - https://github.com/samvera/hyrax/releases/tag/v2.0.0.beta1

### Rationale

Keeping up to date with Hyrax upstream development. Be prepared well for the upcoming 2.0 version release.

**Comment by VivianChu** [comment]
@mcritchlow - After discussing this issue via samvera slack. they suggested me to create new issue for hyrax.  Here's the issue I just created https://github.com/samvera/hyrax/issues/1742
