### ISSUE TITLE
IIIF R&D

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#136]
### Descriptive summary

Initial evaluation of IIIF options, particularly based on the excellent experience written up by Jonathan at CHF: https://bibwild.wordpress.com/2017/08/29/full-res-pan-and-zoom-js-viewer-on-a-sufiahyrax-app/

Of particular interest are:

- Evaluating [Cantaloupe](https://github.com/medusa-project/cantaloupe)
- Evaluating `vips` vs `graphicsmagick` vs `imagemagick` to generate static tilesets (as we've done w/ DAMS4). The performance gains from `vips` as written about, as well as `graphicsmagick` over `imagemagick` seem well worth exploring.

### Rationale

Based on the information we have available, we want to try and make the best decision about what to do with image derivatives.

**Comment by lsitu** [comment]
@mcritchlow I've added initial support for IIIF with OpenSeadragon and Cantaloupe (see PR https://github.com/ucsdlib/horton/pull/137). We can test it  on the demo server once it's ready. Here is the steps to setup and run Cantaloupe:

- Download the latest Cantaloupe release 3.3.2 from https://medusa-project.github.io/cantaloupe/get-started.html.
- Copy cantaloupe.properties.sample and rename it cantaloupe.properties
- Edit FilesystemResolver.BasicLookupStrategy.path_prefix in cantaloupe.properties:
FilesystemResolver.BasicLookupStrategy.path_prefix = /path/to/Fedora/filestore/ 
(For example $HOME/horton/tmp/fcrepo4-test-data/fcrepo.binary.directory/)

Note that Cantaloupe can be configured to use different processor like `GraphicsMagickProcessor`, `ImageMagickProcessor` etc. to handle different file formats and the default is Java2dProcessor. And I think we can configure it to test the performance with GraphicsMagick and ImageMagick later.

**Comment by lsitu** [comment]
@mcritchlow @VivianChu I found a little bug and create another PR to fix it with a couple more tests to improve the test coverages: https://github.com/ucsdlib/horton/pull/138. Thanks.
