### ISSUE TITLE
Update Hyrax (upstream) chinese locale

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#147]
### Descriptive summary

Please update the Hyrax chinese locale file to be up-to-date with the english version.

### Rationale

A Hyrax 2.0 release is coming soon, it would be a great for us to be able to help ensure the chinese locale file is accurate and up-to-date. Note this will need to be done by our team.

**Comment by mcritchlow** [comment]
@hweng or @lsitu - Could one of you take this for next Sprint please? Thanks!

**Comment by hweng** [comment]
@mcritchlow I can take care of it.

**Comment by hweng** [comment]
Updates - My pull request is merged into master branch: https://github.com/samvera/hyrax/pull/2274#pullrequestreview-79663283
