### ISSUE TITLE
Hyrax Migration

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#15]
- [ ] Depends on #21 

Not sure if we're going to do this yet, but placing some links here for reference assuming we do. The discussion, and migration of the Hydra in a box application from Sufia to Hyrax(the consolidated Sufia/CC project).

https://github.com/projecthydra-labs/hyrax/issues/4

https://github.com/projecthydra-labs/hyku/commit/a8b25cdf6630b425c8eed34fabb58b9a14523677

**Comment by lsitu** [comment]
@mcritchlow Unfortunately we may need to work on ticket https://github.com/ucsdlib/horton/issues/21 to upgrade horton to use rails 5.0.0.1 first before migrating to hyrax. I got the following dependency error: 
Resolving dependencies....
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    hyrax (= 0.0.1.alpha) was resolved to 0.0.1.alpha, which depends on
      railties (~> 5.0)

    rails (= 4.2.7.1) was resolved to 4.2.7.1, which depends on
      railties (= 4.2.7.1)
    generate    hyrax:install
The git source git://github.com/projecthydra-labs/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application

What do you think?

**Comment by mcritchlow** [comment]
@lsitu - Yep, looks like they've pinned to Rails 5. Ok, Rails 5 first then.

**Comment by lsitu** [comment]
@mcritchlow I'm trying migrate the [feature/rails5](https://github.com/ucsdlib/horton/tree/feature/rails5) branch and get Object ingest working now. With the structure changes, the migration of collection codes seems to have a little trouble and I am looking into it now.

**Comment by lsitu** [comment]
@mcritchlow I've created PR https://github.com/ucsdlib/horton/pull/23 for Hyrax migration. As noted in the PR, only the CSV Ingest/import support issue haven't been fixed, which is derived from the underlying support with batch ingest in Hyrax.
