### ISSUE TITLE
R&D: Queue options

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#17]
As Hyrax uses `active_job` to support message queues, we have a few options to consider in implementing our own queue system. The two obvious candidates are:

* Resque
* Sidekiq

There is a mix of usage in the community, so we should probably do a little research and ask around for people's experience, particularly as it relates to larger batch processes (since that will be our primary usage of the queuing system). I believe Princeton is using Sidekiq for plum, so that's worth taking a strong look at.

**Comment by mcritchlow** [comment]
After a decent amount of research, it seems pretty clear that Sidekiq is being used by the [majority of the Rails community](http://blog.scoutapp.com/articles/2017/01/09/state-of-the-2017-rails-stack), and I've noticed new Hydra apps are using it s well. It is also noticeably faster and comes with an option for paid support (along with additional features) that we could evaluate in the future.

So perhaps we should adjust this ticket to adding in Sidekiq as the queue solution. @ucsdlib/developers  -- does that reasonable to you all?

**Comment by lsitu** [comment]
@mcritchlow Sidekiq looks good and I am fine with it.

**Comment by mcritchlow** [comment]
@lsitu since this overlaps with your work in #23 and #15 do you think it makes sense to break out any additional configuration/etc. into the scope of this ticket?

**Comment by lsitu** [comment]
@mcritchlow Yes. It sounds good to break it out any additional configuration/etc. into the scope of this ticket. Thanks.

**Comment by lsitu** [comment]
@mcritchlow I am able to setup Resque/Resque Pool and try to use it for CSV/Batch Ingest. I don't see any warnings/errors for ingest and it seems like that the records and thumbnails are showing up faster and in the orders of ingest, while using Sidekiq the order is messing up and often I need to wait longer time for all the records to be showing.
Would you like me to create two different PRs for Resque and Sidekiq configuration so that we all can evaluate them a little bit before making a decision?

**Comment by mcritchlow** [comment]
@lsitu That's interesting. Given everything that I've read, I'd be very surprised for Resque to be faster than Sidekiq. Speed is one of the main things Sidekiq says is has over other solutions like Resque, Delayed Job, etc.. I suspect there might be configuration details, such as adding tweaking the [priority of the queues](https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues),  setting explicit [pooling setup for Sidekiq/Redis](https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control), etc. that we might still need to try out to get the most out of Sidekiq.

That said, evaluating both so we can make an informed decision sounds like a very reasonable plan to me 👍

**Comment by lsitu** [comment]
@mcritchlow I think the problem is the warnings "Error while trying to deserialize arguments" which interrupt the ingest: https://github.com/ucsdlib/horton/pull/23#issuecomment-273218815. But yes, we can review the option later to see whether this warning still an issue or not.

**Comment by lsitu** [comment]
@mcritchlow I've created PRs for [Resque](https://github.com/ucsdlib/horton/pull/25) and [Sidekiq](https://github.com/ucsdlib/horton/pull/26). 
The configuration for Sidekiq includes concurrency setting now. It seems that it's much faster for all records with thumbnails created to be showing up now. And I don't' the warnings like "Error while trying to deserialize arguments" (see https://github.com/ucsdlib/horton/pull/23#issuecomment-273218815). But often I see warnings like "TID-outhrreno WARN: ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked: commit transaction".  This could be the issue of the SQLite3 database that doesn't support concurrency, but there is a couple of times I saw an additional record ingested, which could be an issue. 
Here is the warning I got:
2017-01-18T19:42:19.814Z 16271 TID-outh20vno IngestWorkJob JID-26359c56003473eece9d1444 INFO: fail: 5.365 sec
2017-01-18T19:42:19.814Z 16271 TID-outhrreno WARN: ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked: commit transaction
2017-01-18T19:42:19.814Z 16271 TID-outh20vno WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"IngestWorkJob","queue":"ingest","args":

**Comment by mcritchlow** [comment]
@lsitu - ah, yep. SQLite can't do concurrent access as you noted. So it looks like we'll need to get it setup with a proper postgres DB.

I think the additional record ingest could be either an issue as a result of the concurrency we're seeing and SideKiq's attempt to retry, or a bug in one of the jobs as you noted. Sidekiq does make it pretty explicit that the jobs [need to be idempotent](https://github.com/mperham/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional), which is what makes me wonder if this issue will go away with a non-locking DB addressing a potential assumption on the part of the hyrax jobs. Definitely something we want to keep an eye on though, as like you said it could be a legitimate bug we'd need to report and/or look into.
