### ISSUE TITLE
R&D: Integration of ARK Minter

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#24]
Horton is currently using the out-of-the-box AF:NOID functionality.

Task:

- [ ] Identify how to change the minter configuration to using our ARK minter
- [ ] Document this in the README, or elsewhere as agreed upon by group.

If time permits, we can adjust this ticket to include the actual changes necessary including, but not limited to:

- [ ] add code/configuration to use ARK minter (dependent on environment)
- [ ] add tests to demonstrate that ARK minter is being used

**Comment by lsitu** [comment]
@mcritchlow Looking into the AF:NOID module, I found it supports internal minter by default and won't be able to support external ARK minter by configuration. If we want to support external ARK minter, we may need to create a custom minter to override it. But we can disable AF:NOID and to mint IDs from Fedora, which is the the default behavior. In this case just use the configure in Fedora for the external ARK minter.
If we don't want to setup the external ARK minter server locally for development and test, which is not so convenient, I think we may need to find a configurable way to enable the external ARK minter for a specific environment and use the default AF:NOID for other environments like test and development. Or we can simply configure it to mint the IDs from Fedora. What do you prefer?

**Comment by mcritchlow** [comment]
@lsitu - I think that plan makes good sense. AF:NOID for dev/test environments and configure Fedora to mint ARKS for prod. We have been using the dev minter for our current test environment, so we could potentially continue that practice as well.

**Comment by lsitu** [comment]
@mcritchlow Yes, we can override the default AF:NOID to use the dev minter for test. But we can simply let the default AF:NOID take care of it without any code changes though. I think we may need to make the decision regarding what ARK minting strategic for each environment when moving forward.

**Comment by mcritchlow** [comment]
@lsitu yep, that's one of the TODO's in the original part of this ticket. Dev and Prod seem pretty self-explanatory. So we probably just need to discuss pros/cons of the test environment minter options and make a call.

**Comment by lsitu** [comment]
@mcritchlow I've added the configuration support to enable the using of Fedora IDs that was support to has ARK minter integration. See https://github.com/ucsdlib/horton/commit/ae9e50c8a0f1dfb0f2dadefd4eab90e555ce8e9d.

**Comment by mcritchlow** [comment]
@lsitu that looks great 👍
