### ISSUE TITLE
Auto-complete fields with long CVs

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#27]
Some of our form fields, such as Language, will have a long list of potential matches from CV lists. 

We should:
* look into what options we can leverage from Hyrax and QA "out of the box"
* Review those options with @ucsdlib/domm 
* Determine what customization needs, if any, there are and document and perform that work

**Comment by lsitu** [comment]
@ucsdlib/domm Looking into the support from Hyrax and QA "out of the box", I can't find much options but the build-in auto-complete with QA works in this case and I've created a PR with commit https://github.com/ucsdlib/horton/commit/b7c49e463143e74adee314e405b21b53d3fe08b3 for language support.
With auto-complete, when we type in more than two characters in the language text input box, a query will sent to QA and the select options will be showing up for you to choose. The language label submitted with the form will be translated to the corresponding URI internally. If an invalid language label submitted, the form will be rejected with a validation error message.
Do you have any questions regarding this implementation?

**Comment by remerjohnson** [comment]
@lsitu Looking over the language vocabulary, pulling up auto-complete after 2 characters seems like a good "sweet spot" interaction-wise. I imagine we could demo this at a future sprint review, rolled into other developments?  

@mcritchlow We will also need this functionality for "roles" at some point...  unfortunately I don't believe that [DMPS settled on the specifics of vocabularies](https://lisn.ucsd.edu/display/mpg/DMPS+2016-12-07) so I'm not sure how to proceed there.

**Comment by lsitu** [comment]
@remerjohnson Yes I think we could demo the auto-complete feature sometime in a future sprint review.

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments ... Thanks.
