### ISSUE TITLE
R&D porting the existing pilot codes to add A-Z links to Facet view pages

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/horton#3]
This will include the following feature in dams5-cc-pilot:
https://github.com/ucsdlib/dams5-cc-pilot/issues/33

**Comment by hweng** [comment]
Porting code for this feature has been implemented in https://github.com/ucsdlib/horton/pull/5

**Comment by mcritchlow** [comment]
@hweng this work was completed, right?

**Comment by hweng** [comment]
@mcritchlow  I think most is done. Maybe just need to update the catalog_controller configuration to upper-case letter for  A-Z links.

**Comment by mcritchlow** [comment]
OK, so enhancing what you've done in this ticket already. I'll set that up as a new ticket for next Sprint. If there are other related blacklight things we should port, please let me know.
