### ISSUE TITLE
Add Coveralls/Hound CI reporting

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#34]
Following the work @hweng did on https://github.com/ucsdlib/billing-ill/issues/98

Please add Coveralls and Hound CI to this repo.

For linters, let's start with rubocop. We can also discuss CSS/JS options, but it doesn't have to be in scope for this ticket.

**Comment by hweng** [comment]
@mcritchlow Should I remove ENV['TRAVIS'] or remove the whole method of coverage_needed? and the "if coverage_needed?" condition https://github.com/ucsdlib/horton/blob/develop/spec/spec_helper.rb#L5 ?

**Comment by hweng** [comment]
@mcritchlow I prefer to remove "if coverage_needed?" condition. What do you think?

**Comment by mcritchlow** [comment]
@hweng yeah, I agree. That looks historical, and not particularly relevant now. We're definitely not using Travis, and we're pinned to Rails 5+.
