### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#37]
The `README.md` file should be updated to address the following:

- [x] Remove line about the repo being for spikes only. We're past that point, this is the real deal 😄 
- [x] Add a line about starting `redis-server` to the startup instructions, that appears to be a gap
- [x] Add badge for Coveralls
- [x] Add badge for Gemnasium

**Comment by lsitu** [comment]
@mcritchlow It looks like we may need an account on Converall to create the badge for horton. The url should be something like https://coveralls.io/repos/ucsdlib/horton/badge.svg. How should we proceed with it?

**Comment by mcritchlow** [comment]
@lsitu - I added coveralls for horton. cc/ @hweng since that's relevant for #34 

You should be able to login with your GH account and see the details here: https://coveralls.io/github/ucsdlib/horton If not, let me know.

**Comment by lsitu** [comment]
@mcritchlow Yes, I can see it now. Thanks.

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments ... Thanks.
