### ISSUE TITLE
Statistics Requirements

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#41]
### Descriptive Summary

We currently have all our statistics managed internally by DAMS Manager.

The scope of this ticket is to gather and document the requirements for DAMS5 statistics. This can be in the form of use cases or user stories.

Once we have this information, we should share with Mike Giarlo and get a sense of how many of our gaps might be worth filling at the Hyrax vs local level.

### Related Work

@VivianChu will be adding default Hyrax support in #44

**Comment by lsitu** [comment]
@mcritchlow Do we have a google account to support Google Analytics, or we have to use our own private account to create the horton project and the service account with credentials for the support?

**Comment by mcritchlow** [comment]
@lsitu - I believe we have a generic account that might work. I'll check. Also just noting that this ticket isn't quite ready for work yet, it's just a placeholder for now while we gather information.

**Comment by lsitu** [comment]
@mcritchlow That sounds great if there is a generic account for it. I was looking into the materials for the support yesterday, and I won't work on it until you think it's ready. Thanks.

**Comment by mcritchlow** [comment]
An update on this:

* @gamontoya and @hjsyoo will work on gathering and documenting requirements
* Operations is working on a general GA account we can use for setting up credentials/keys needed for Hyrax integration

**Comment by mcritchlow** [comment]
Note: I'm going to split this ticket into 2. One for requirements gathering (assigned to Gabriela and Ho Jung) and the other for initial setup and configuration ( @VivianChu is going to work on that part)
