### ISSUE TITLE
Port WYSYWIG support

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#53]
### Descriptive summary

Please port/recreate the ability for users with curator access to edit (and possibly create) new pages that they are able to edit themselves.

Examples under the Help menu of Digital Collections app.

While this feature is currently implemented in damspas in the following manner, this need not be the exact same implementation in Horton. If there are other options that may be a better fit, please feel free to recommend one. Ultimately, it is the functionality/feature that needs to migrate.

* https://github.com/ucsdlib/damspas/commit/6c5b536a86df4f251d815b2094f80d1580ab9433
* https://github.com/ucsdlib/damspas/commit/e3f2ba2efe6b25396791f8c0628d8b4d686d046a 

### Rationale

Curators would like to continue being able to update content for static pages without relying on the deploy cycle for the application.

**Comment by hweng** [comment]
@mcritchlow  I figured out the problem that RSpec/FactoryGirl leaves record in test database after each test case is completed, which is messing up other tests: The "config.use_transactional_fixtures" should turn to "true"
https://github.com/ucsdlib/horton/blob/develop/spec/spec_helper.rb#L47

It works fine now after update the above line.
