### ISSUE TITLE
Port auto-linking feature

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#54]
### Descriptive summary

Currently in DAMSPAS, a hyperlink in any displayed text is "auto-linked" via the Rails autolink gem [1]. We need to port this feature to Horton.

If there is a newer/better gem that provides the same functionality, please feel free to recommend.

1. https://github.com/ucsdlib/damspas/blob/develop/Gemfile#L26 

### Rationale

The feature is expected behavior for a variety of metadata fields, such as Description, which frequently reference external URLs. As a result, this feature needs to be ported to Horton.

**Comment by hweng** [comment]
@mcritchlow rails_autolink gem has been added to horton. What page or fields to add auto_link?

**Comment by mcritchlow** [comment]
Great question. This is most applicable to notes in the object and collection view pages. How granular are we getting in the current damspas application? Do we get down to the individual field level?

**Comment by hweng** [comment]
In damspas, the auto_link is applied to the following files:

views/catalog/_collection.html.erb
views/shared/fields/_custodial_responsibility_note.html.erb
views/shared/fields/_note.html.erb
views/shared/fields/_preferred_citation_note.html.erb
views/shared/fields/_scope_of_content.erb

**Comment by mcritchlow** [comment]
Perfect. So I think, for now, mapping to the equivalent of that in horton, following the new data model map and hyrax design patterns.

If we haven't migrated everything yet, perhaps we can cover what we can for now, and then create a separate issue for things we can't yet cover?

**Comment by mcritchlow** [comment]
A related question, is there any support in Hyrax for this already we can use or take advantage of?

**Comment by hweng** [comment]
Yes, It is already support in Hyrax:
https://github.com/projecthydra-labs/hyrax/blob/master/hyrax.gemspec#L53

**Comment by mcritchlow** [comment]
Great! So, do we need to explicitly do anything on our end? Or are rendered fields already wrapped with `auto_link`?

**Comment by hweng** [comment]
@mcritchlow  Here is the screenshot which shows the auto_link has been applied already, looking at the General note and Description fields:
![screen shot 2017-03-21 at 11 26 59 am](https://cloud.githubusercontent.com/assets/2432753/24164041/aa54450a-0e29-11e7-95bc-0f212ddd4e15.png)

**Comment by mcritchlow** [comment]
Perfect, thanks @hweng. I'll mark this closed then!
