### ISSUE TITLE
Port Advanced Search

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#57]
### Descriptive summary

damspas currently uses an older version of the Blacklight Advanced Search plugin [1].

Please add the latest version of this plugin to Horton and mirror the configuration from damspas as much as it is practical. Please comment if configuration issues arise we should discuss, but the idea is for an "out of the box" evaluation of the latest plugin prior to any significant configuration changes.

1. https://github.com/projectblacklight/blacklight_advanced_search  

### Rationale

In order for stakeholders to evaluate whether the newer plugin will satisfy the advanced search needs for DAMS5, we need to install the latest plugin in Horton.

**Comment by hweng** [comment]
@mcritchlow I got latest version of advanced search integrated into hyrax.  It works fine now after fix some issues with hyrax.  And most of advanced search form code from damspas can't be ported into hyrax as its blacklight version is too far behind.

Here are some screenshots:
<img width="1229" alt="screen shot 2017-03-17 at 12 29 24 pm" src="https://cloud.githubusercontent.com/assets/2432753/24061044/14bdaeaa-0b13-11e7-9a44-233991fadecc.png">

<img width="1143" alt="screen shot 2017-03-17 at 12 29 49 pm" src="https://cloud.githubusercontent.com/assets/2432753/24061052/212b2e10-0b13-11e7-81b2-6da8962a5fc8.png">

**Comment by mcritchlow** [comment]
Perfect, thanks for the screenshot as well. This is a perfect starting point for evaluation and further discussion 👍
