### ISSUE TITLE
Finalize "Related resource" property in import template and ontology 

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/horton#58]
### Descriptive summary

We need to finalize an approach for "related resource", stemming from csv import template #46 

Focusing on "Related Resource":
  1. How it will be modeled going from D4 -> D5
  2. How to represent it in the ontology (currently range is `xsd:anyURI`). Do we need a new class with properties? 
  3. How to represent it / encode it in the D5 object import template. 

Deliver: 
  * (optional but would be helpful) An example output from D5 showing related resource metadata
  * Update the [4.2 data dictionary](https://docs.google.com/spreadsheets/d/1OjTm1Kuzo-An-THdpUkjwa5puul-b4Lx3SK0lB6rvl8/edit#gid=616154196) for related resource properties (if any changes) 
  * Update the delimited import template (if any changes)

### Related work

Ticket spawned off from ucsdlib/horton#46

**Comment by remerjohnson** [comment]
A little background: DOMM yesterday wanted to maintain the current "Related resource" use where we input the label and a URL, like `Calit2 @ http://www.calit2.net` One concern was these are mostly unstable links we point to. 

But, we were also concerned since the current range for our related resource properties are just `xsd:anyURI`. We didn't know if this meant we would need to turn this into a class or not. So if we can see what it would look like in D5 I think it would enlighten us on how to move forward. @lsitu @mcritchlow

**Comment by lsitu** [comment]
@GregReser What predicate would you like to use as the global relatedResource property if we embed the type property in the RelatedResource class? And what predicate should we use for the type in RelatedResource?

**Comment by ghost** [comment]
@remerjohnson what do you think - go with the separate related resource predicates on rows 119 - 127 of dams4.2 data dictionary or a RelatedResource class?

**Comment by remerjohnson** [comment]
@GregReser @lsitu Longshou, we recently have made all Related Resource types into their own predicates (see the 4.2 mapping), with a range of "Schema:Intangible".  

This was speculative. I would appreciate your input to whether this works from a data migration, and also a modeling standpoint. Also of course would like to know @mcritchlow thoughts.

**Comment by lsitu** [comment]
@remerjohnson How would you like the Schema:Intangible to be created/managed, just like ucsd:Agent, Concept, etc that need to be created independently before ingest, or something that need to be created dynamically in the ingest form/Excel spreadsheet through blank nodes support? 
It looks like there are more than 10 fields defined in the [Schema:Intangible](https://schema.org/Intangible) class. How many fields are required for implementation?

**Comment by remerjohnson** [comment]
@lsitu These would have to be recorded much like they currently are, in the ingest form. We can devise a scheme for how to do that, but no, these would not have to go in like Agents and Concepts before ingest. Since we cannot ensure the persistence of these links, we do not want to treat them like those kinds of entities.

Currently if you scroll down to the very bottom of the 4.2 dictionary [line 264+](https://docs.google.com/spreadsheets/d/1OjTm1Kuzo-An-THdpUkjwa5puul-b4Lx3SK0lB6rvl8/edit#gid=616154196&range=264:264), we have the properties we'd need listed. They are basic: `schema:name`, `schema:identifier`, and `schema:url`

**Comment by lsitu** [comment]
Got it, thanks @remerjohnson. 
So you just want to use the class name as Schema:Intangible for all related resource? And each related resource type has its own predicates, like ucsd:depiction, ucsd:exhibit, ucsd:findingAid etc?

**Comment by remerjohnson** [comment]
@lsitu correct... I think we might have to page @mcritchlow to get thoughts. I could maybe see this looking simpler on paper than in the RDF for an object...

**Comment by lsitu** [comment]
@mcritchlow I think we could get it work through blank nodes support by either using a type property within the class (like what we did for ucsd:Agent) or have different predicates for each related resource as @remerjohnson proposed above. What do your think?

**Comment by mcritchlow** [comment]
It seems like a very subjective decision to make.. I spoke a bit on Slack with @remerjohnson and @lsitu trying to weigh the pros and cons. Given all that, I think using predicates for the related resources types will make our lives slightly easier in a couple areas of use. This is assuming we won't be consistently adding new types over time, or I would definitely recommend we go the other way.

I also spoke with Ryan on the existing types and it is striking that 4 or so of them (more or less half) are for Levy's collection alone. I wonder if we can reconsider that. One idea, since all our fields in the new system will be auto-linked, is we could fold those into a note field for that collection? Maybe scope creep for this ticket, but it seems unbalanced to have that many types for one collection.

**Comment by ghost** [comment]
I have no problem using predicates for the related resources types if they will make things easier.
On a "related" topic... for related resource:related, since range will now be a class, I think we should use dc: (dcterms) instead of dc11:, which is intended for a string value.

**Comment by remerjohnson** [comment]
@mcritchlow Is it possible for us to actually use `dc:relation` now for `related resource: related`? I feel like us having a range of `Schema:Intangible` might rule that out...

**Comment by lsitu** [comment]
@remerjohnson I try to use the property name relation but getting invalid name violation. It look like it's used by the Hydra app but using related works. Do you need to change the property name to 'relation' or not?

**Comment by ghost** [comment]
on https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb 
I see they are using property :keyword, predicate: ::RDF::Vocab::DC11.relation

So keyword is relation?  Strange

**Comment by lsitu** [comment]
@GregReser I think the keyword `relation` could be used somewhere else, like ActiveTriple. But we can change the predicate from dc11 to `dc:relation` now.  And I think we can change the label later in the UI level if you want. Does it sound good?

**Comment by lsitu** [comment]
@GregReser @remerjohnson I try it again and don't see that error now. So I think we can use it. So are you going to change the column name to `related resource: relation`  instead of `related resource: related`?

**Comment by ghost** [comment]
I think related resource: related conveys the meaning better.  We  have other column names that don't match the predicate, so it's not a strict rule we are following.

**Comment by lsitu** [comment]
@GregReser @remerjohnson I think we've implemented the nested resource with blank nodes support. Now we are able to create related resource dynamically on ingest time or through the edit form. Attached is the screenshot of the edit form: 
<img width="1353" alt="screen shot 2017-03-30 at 1 15 11 pm" src="https://cloud.githubusercontent.com/assets/2430784/24525468/3e66c052-154f-11e7-9572-4805ebf3ffd3.png">

But if we use lots of nested resources/blank nodes, the form will become extreme large and the using of too many embedded fields will impact the performance of loading the edit form a lot. I'll suggest only use nested resource if we have to. Are there any fields that may require less changes? I think we can use the QA gem to manage it in this case, just like Language. And how's @mcritchlow's [suggestion](https://github.com/ucsdlib/horton/issues/58#issuecomment-289844119) for those fields used by Levy specifically?

**Comment by remerjohnson** [comment]
@lsitu Is there a way we can have _one_ Related Resource box (keeping the option to "Add another"), and that would have a dropdown box that would drive the different predicates we have? 

The dropdown could default to the normal 'Related'. Or is this not possible?

**Comment by lsitu** [comment]
@remerjohnson Then I think we had better remodel/extend the Intangible class to include a type property. Otherwise it could be painful for the implementation.

**Comment by remerjohnson** [comment]
@GregReser `schema:Intangible` has an `additionalType` [property](https://schema.org/Intangible) that expects a URL. It'd be a bit strange because we'd have to just have the one (dc terms) `dc:relation`, then specify the types via URLs within `Intangible`... 

```
dc:relation   [ a   schema:Intangible ;
                schema:additionalType  damsid1234 ;  # this is a URI to a related resource type
                schema:name            CalCOFI Web Site ;
                schema:url             http://www.data.calcofi.org/
              ] ;
```

What do you think?

**Comment by ghost** [comment]
@remerjohnson It's not a bad idea.  What's the motivation to move from separate related resource predicates - implementation in the edit form (repeatable related resource with type dropdown?

**Comment by remerjohnson** [comment]
@GregReser Right, @lsitu was saying our current multiple predicates would bog down the edit form. 

I would be fine with moving Levy-related resource types to just notes as @mcritchlow suggests, but I believe @arwenhutt wanted to preserve current functionality.

**Comment by ghost** [comment]
How are creators handled in the edit form?  I can't imagine having every creator predicate as a separate, always visible field.  Can a dropdown be used to select the predicate?  If so, can this be done for related resource?

**Comment by remerjohnson** [comment]
@GregReser I don't know. This is what I [proposed earlier](https://github.com/ucsdlib/horton/issues/58#issuecomment-290568498), but was told it'd be easier to extend it with types.

**Comment by lsitu** [comment]
@GregReser @remerjohnson I think the handling of creators/MARC Relators in the UI should be a different issue that we can talk about later, in which we create the ucsd:Agent in advance that we can choose from in the form, which is different from the blank nodes support we have here for the related resources.

**Comment by lsitu** [comment]
@GregReser @remerjohnson We are going to merge the PR above now.
Are we going to keep the current implementation and seeking solution for those related resources specifically for Levy as Ryan's [comment](https://github.com/ucsdlib/horton/issues/58#issuecomment-291202850) above, or remodel the class with a type?

**Comment by arwenhutt** [comment]
@lsitu @GregReser @remerjohnson I think this conversation might benefit from a phone call/meeting.  I think we are having some trouble disentangling the UI and the modeling, which I think will be easier to clear up with a synchronous conversation.

**Comment by lsitu** [comment]
@GregReser I found we can't use property name "type" in related resource. It's reserved for rdf:type in hyrax. Could we use "related type" instead?

**Comment by ghost** [comment]
@remerjohnson how about "relatedType" since we are using "agentType" in the ucsd:Agent class?

**Comment by lsitu** [comment]
I think we just need to updated the property name for the Related Resource class in the data dictionary. And it's fine if you still want to "type" in the Object Import template like "formatted string = label @{type=CV; uri=value}" for convenience, but we need to add it to the "Formatted key-value rules" tab for validation.

**Comment by lsitu** [comment]
@GregReser Also, should we change it to use url in the Object Import template instead of uri since it's defined as url (schema:url) in the RelatedReource class?

**Comment by ghost** [comment]
OK, we'll use "relatedType" in the data dictionary Property Label

In the Object Import template, related resource formatted string = label @{type=CV; url=value}

**Comment by lsitu** [comment]
It sounds good! Thanks. Could we update the keys in the "Formatted key-value rules" for the type and url as well? We use it for keys validation.

**Comment by ghost** [comment]
To avoid confusion and make validation easier, should we use the key "relatedType"

label @{relatedType=CV; url=value}

**Comment by lsitu** [comment]
Let's use relatedType then. And I'll update the codes for it. Thanks.

**Comment by ghost** [comment]
OK, template updated.

**Comment by lsitu** [comment]
I've updated my codes to use the latest import template. Thanks @GregReser .

**Comment by lsitu** [comment]
We've implemented the related resource with relatedType in ticket https://github.com/ucsdlib/horton/issues/67. So I think we can close the ticket now.

**Comment by remerjohnson** [comment]
@lsitu Thanks! I'll close now
