### ISSUE TITLE
Create Chinese internationalization locale for Hyrax

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#61]
### Descriptive summary

Please create a Chinese locale file to live alongside the Spanish and English instances in the Hyrax repository [1].

The deliverable from this ticket should be a chinese locale that is submitted via a Pull Request to the Hyrax repository. Please reference this ticket in the PR when it is created, so it's tracked appropriately.

1. https://github.com/projecthydra-labs/hyrax/tree/master/config/locales

### Rationale

The Hydra community has been making strides at internationalization efforts lately, and now support both Spanish and English. UCSD would like to contribute a Chinese locale to enable browsing by native speakers.

### Expected behavior

Following the creation of the Chinese locale yaml file, the drop-down menu for locale that currently allows a selection of English and Spanish should include an option for Chinese.

**Comment by mcritchlow** [comment]
@hweng - is this ready to go in a Sprint yet?

Could you also write a brief summary about your meeting with Shi Deng, and list out any next steps you both agreed to? Thanks.

**Comment by hweng** [comment]
@mcritchlow Yes, it can go in this sprint.

**Comment by mcritchlow** [comment]
@hweng - great, thanks!

**Comment by hweng** [comment]
The Hyrax issue has been created: https://github.com/projecthydra-labs/hyrax/issues/793

**Comment by hweng** [comment]
The rubocop format issues and test fails have been fixed. My pull request has been approved and merged into Hyrax master branch: projecthydra-labs/hyrax#794

**Comment by hweng** [comment]
https://github.com/projecthydra-labs/hyrax/pull/794
