### ISSUE TITLE
Implement Identifier support

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#62]
### Descriptive summary

Following a meeting with @ucsdlib/domm there was agreement to model identifiers as individual predicates, as opposed to the custom URN syntax we had previously documented. 

@GregReser will be identifying and documenting the predicates to use as a starting point

@lsitu will implement these predicates and related support for ensuring the distinction between public/private identifiers are carried through from DAMS4.

### Related work

Link to related tickets or prior related work here. TBD

**Comment by lsitu** [comment]
@GregReser Please let me know if it's ready for me to implement it. Thanks.

**Comment by ghost** [comment]
@lsitu This is ready to implement.  I have updated the new template with the identifier predicates and public/private UI view status (rows 97 to 118)
https://docs.google.com/spreadsheets/d/1EhMWaDFsBZDhp-BU-5LtOI0tECDx2EtAZ28iZk-Ih58/edit#gid=559462679

Note that I introduced a new namespace: locid = http://id.loc.gov/vocabulary/identifiers

**Comment by remerjohnson** [comment]
Whoops, just commented on this in Slack but @mcritchlow per our discussions on ORCIDs, since this will be a property within Agents, I put that there and crossed it out above in the spreadsheet. Just a heads up.

We'll use that same new namespace, though

**Comment by lsitu** [comment]
Thanks @GregReser. Just some questions regarding the implementation:
Is identifier a class or just Literal value?
Are we going to encode the public/private property into the identifier?
For properties naming convention, Ruby doesn't favor hyphenated names/symbols, could we use camel case/underscore instead of hyphenated names?

**Comment by ghost** [comment]
@lsitu 
identifier is a literal
We do not have a way to encode public/private in the identifier.  The thought was to include these in the UI display logic.  Is that possible?
Yes, let's use an underscore. e.g., ucsd:id_accession.  I'll update the spreadsheet.  I also added these to the dams4.2 data dictionary Google spreadsheet.

**Comment by ghost** [comment]
@lsitu On second thought, let's use camel case instead.  ucsd:idAccession

**Comment by lsitu** [comment]
Thanks @GregReser. Yes, I think we only can hardcode those private identifiers for UI display if the identifier doesn't contain any public/private infomation.

**Comment by ghost** [comment]
@lsitu I updated the template with camel case.  I also removed identifier:orcid because it will now be in the Agent class.

**Comment by lsitu** [comment]
@GregReser It looks like that the labels for locus and news release are conflicting with the labels use for Related Resource, and the filename is conflicting with a symbol use in files by hyrax too. Do you have any suggestions on renaming the labels for locus, news release, filename?

**Comment by ghost** [comment]
@lsitu You're right about the conflicts.

I have updated these identifiers:
identifier:basket number
identifier:locus number
identifier:oclc number
identifier:registration number
identifier:roger record

For identifier:filename, do you mean that filename conflicts?  How about identifier:file name?

**Comment by lsitu** [comment]
Yes, it sounds good. Thanks @GregReser.

**Comment by lsitu** [comment]
@GregReser Do you have any thoughts on news release? I notice that you may have misplaced the Property name to the "Predicate" column for the identifiers in the [data dictionary](https://docs.google.com/spreadsheets/d/1OjTm1Kuzo-An-THdpUkjwa5puul-b4Lx3SK0lB6rvl8/edit#gid=616154196). Are we going prefix "identifier:" for the property name? Ruby doesn't favor the ':' for property name either.

**Comment by mcritchlow** [comment]
Another naming pattern to consider, just to throw it out there, is something like the following using an `_id` suffix.

So:
```
basket_id
locus_id
oclc_id
...
```

**Comment by ghost** [comment]
to differentiate from related resource, right?  Should we do this then?

basket_id
basket_related

**Comment by lsitu** [comment]
The naming pattern looks good to me. The property name/label will be displayed on the edit form and the object viewer with the underscore replaced by whitespace. So I think a label/name that would help understand that piece of metadata will be good.

**Comment by ghost** [comment]
Let's use _id for identifier names.  Should the predicate use the same format for consistency and ease of understanding?
ucsd:basket_id

For related resource - let's wait until I get feedback for Arwen and Ryan.  We still have to figure out the relatedResource range anyway.

**Comment by ghost** [comment]
If the property name/label will be displayed on the edit form and the object viewer, we probably shouldn't use names like "createdDate", right?  This would display as "CreatedDate" in the form?

**Comment by lsitu** [comment]
I think if we need our own ucsd namespace predicate, then it's good to make it inline with the property name (the CamelCase version? it looks like CamelCase is used for predicates normally). But we can use any predicates from any namespaces that you think a match. For a  CamelCase property name like "createdDate", I just change it to "created_date" so it would show up as "Created date". And yes, the label will be capitalized when displaying on the form and the object viewer.

**Comment by ghost** [comment]
I want to make sure we are talking about the same things - property name (column P in dams4.2 data dictionary) Predicate (column R).  I'm guessing that property name (column P) is irrelevant to the labels displayed in the edit form and the object viewer.

The edit form and the object viewer will by default display the predicate unless you override that with a custom label, such as "created_date".  Is that right?  Looks like most predicates are camel case and will need custom labels.

What about automatic capitalization?  Would "basket_id" display by default as "Basket Id"?  We could make it "basket_ID" if that means less work.

**Comment by lsitu** [comment]
@GregReser 
I want to make sure we are talking about the same things - property name (column P in dams4.2 data dictionary) Predicate (column R). I'm guessing that property name (column P) is irrelevant to the labels displayed in the edit form and the object viewer.
** Yes, we are talking about the property name (column P in dams4.2 data dictionary) Predicate (column R). And the property name (column P) is **relevant** to the labels displayed in the edit form and the object viewer.

The edit form and the object viewer will by default display the predicate unless you override that with a custom label, such as "created_date". Is that right? Looks like most predicates are camel case and will need custom labels.
** No, the edit form and the object viewer always display the property name (column P). I just override the CamelCase like "createdDate" in the property name (column P) to "created_date" so that it will display as "Created date" but not "Createddate".

What about automatic capitalization? Would "basket_id" display by default as "Basket Id"? We could make it "basket_ID" if that means less work.
**The automatic capitalization from hyrax will capitalize the first character in the property name and convert any letter that follows to lower case. My tests showing that both "basket_id" and "basket_ID" will display as "Basket id" by default. It seems that this kind of tricks won't work for capitalization by default but I think we can do customization in the UI level for those designated displays later.

**Comment by lsitu** [comment]
@GregReser Sorry I just corrected my comment for your first question above. I mean the property name (column P) is relevant to the labels displayed in the edit form and the object viewer.

**Comment by ghost** [comment]
@lsitu  Thanks for the clarification.  If the label comes from column P, then I should just use spaces for all the names.  We already have many names like this, e.g., "field assistant".

On the other hand, if you have already coded for the names in column P then I don't want to make you change it.

**Comment by lsitu** [comment]
@GregReser Yes, I've coded for all the names in column P. But we should change those for the identifiers to the label you want since we are working on it at this time. For other names, I think we can do it later as a global update.

**Comment by ghost** [comment]
@lsitu OK, it's not worth changing the other labels now, let's just deal with identifiers.

For identifier labels, let's use an underscore "accession_id"
We'll do the same for ucsd namespace predicates "ucsd:accession_id"

I have updated dams4.2 data dictionary and object_import_template.xlsx.  Does that look OK to you?

**Comment by lsitu** [comment]
@GregReser It sound good to me but just not sure whether using underscore for predicates will cause other issues with url access in some cases or not. Maybe CamelCase name for predicates is a better option?

**Comment by mcritchlow** [comment]
On a somewhat related note, I think we should ensure we're being consistent with our naming convention. So either CamelCase everything, or underscore everything.

FWIW, I think @lsitu is right, CamelCase does seem to be the common naming convention used for RDF classes/predicates.

**Comment by ghost** [comment]
I misunderstood @mcritchlow earlier note about "_id". I thought that was for the predicates.  Yeah, all our other predicates are camelCase and it would be good to stick with that.

For the identifier predicates, how about "ucsd:basketId"?

For the property names in column P of dams4.2 data dictionary - those don't show up anywhere in the RDF - they are just used to internally to create UI labels, right?  If that's true, camelCase doesn't really work if you have to convert to underscores or whitespace for the labels.

I was thinking it would help keep us on the same page if we coordinate the ingest template headers with the labels in column P.  I don't know about using prepend labels like "note:related publications" in column P though.  At the least the name after the prepend labels could be the same between lists, e.g., "related publications"

**Comment by mcritchlow** [comment]
@GregReser No, that one is on me :) I thought in terms of Ruby property syntax when I said that, since underscores translate well into Ruby method names, etc. But on second thought, @lsitu is totally right that RDF classes/properties overwhelmingly use CamelCase. So yeah `basketId` is probably better than `basket_id`

**Comment by ghost** [comment]
Cool, I updated the identifier predicates in dams4.2 data dictionary and object_import_template.xlsx

**Comment by lsitu** [comment]
It looks good, thanks @GregReser and @mcritchlow. Just let you know that I'll still following the original coding convention to separate the camelCase property name with underscore so that it'll display as single words for now. For example, "callNumber_id" will be "call_number_id" and displays as "Call number id" by default.

**Comment by lsitu** [comment]
@GregReser Just one thought that if we can make the value after : of the "Header label" column in object_import_template.xlsx to inline with the Property (P column) indams4.2 data dictionary, it'll  event be better for automatic mapping of the "Header label" to the object properties. What do you think?

**Comment by lsitu** [comment]
Also, are there any identifiers that will be used for collections as well?

**Comment by ghost** [comment]
@lsitu Make the value after : of the "Header label" column in object_import_template.xlsx to inline with the Property (P column) indams4.2 data dictionary - yes, that's a great idea!  It will be easier for documentation and for coding - no more translating between different lists.  
For human readability, whitespace is better.  How about for coding, is an underscore necessary for hyrax?  If so, we can use underscores.
Let me know if you are ready to do this (could be done later) and I will update both spreadsheets.

Identifiers that will be used for collections: Yes, we need to support this.  An example would be Identifier:doi in http://library.ucsd.edu/dc/collection/bb87730652

**Comment by lsitu** [comment]
@GregReser I am fine with whitespace for the property names in both list, and actually I simply translate the whitespace into underscore for implementation that Ruby favor. 
I'll add all identifiers support for collections but just added the Identifier:doi to the edit form for now. I think we can adjust it later. Thanks.

**Comment by ghost** [comment]
@lsitu Great.  Are we changing the property labels and headers now, or later?  Either is fine with me.

Also, you'll see some cells in yellow on object_import_template.xlsx.  These are still being decided.  Be prepared for more agent headers.  We entered a few to get you started, but the full list is going to be very big (actually it's the same list we currently use, with a couple of additions).

**Comment by lsitu** [comment]
@GregReser I need to implement the support for the identifiers now and create a PR for review today, so it'll be nice if you can update the property names for the identifiers now. Thanks.
But if there are no changes to the dams4.2 data dictionary, then it doesn't matter and we can change it later.

**Comment by ghost** [comment]
@lsitu Sorry for the endless questions...
Some properties can be hard to understand without the string before ":"  For example, "issue"  is really "date:issue"
How about if we use the exact same values in both "Header label" column in object_import_template.xlsx and Property (P column) indams4.2 data dictionary?  This way it is very clear what the meaning of each property is.
Example:
date:created
date:event
date:collection
date:copyright
date:issue

You would then have to split after the ":" to generate the UI label.  In some cases we might want to customize the UI labels for clarity, like for identifiers.

**Comment by lsitu** [comment]
@GregReser Follows your notes I see the ":" in the Property names in in dams4.2 data dictionary now. Was it changed recently? I think it's good to keep both list consistent and as @mcritchlow [noted above](https://github.com/ucsdlib/horton/issues/62#issuecomment-286882863), we had better use the same pattern for all properties names. I see some with white space, some with underscore, and some are camelCase.
I think the property name should be something that we want to display as label by default. How about interpreting the ":", camelCase, "_" and whitespace the same as whitespace for UI display? In this case, I'll translate ":", camelCase, and whitespace to underscore for implementation so that it can display properly in the UI? Or just ignore the string before ":" for UI display by default?

It looks like we may need a global update/implementation for the naming changes. Could we just do it for the identifiers for now with this ticket? @mcritchlow What's your suggestions?

**Comment by remerjohnson** [comment]
Hmmmm, well if we want the property to be what we want to see in the UI, I would imagine we'd need some work to do in the 4.2 sheet...

**Comment by lsitu** [comment]
@remerjohnson I just mean displaying the translated property name by default. And yes, we can use the property name we want in dams4.2 data dictionary and adjust the display label later in the UI level.

**Comment by ghost** [comment]
@lsitu yes, I was changing some names in dams 4.2 data dictionary as a test for readability.
For many properties, the default UI display can ignore the string before ":", but not always. 

We have some names with more than one ":"
note:material details:water depth

In the new UI, we will probably do something similar to our current UI, where we list all related property types beneath one label:

Material details
 - water depth
 - limits

**Comment by ghost** [comment]
@lsitu I have synchronized the object_import_template headers and dams4.2 data dictionary property names.
I also changed the Title names to be more consistent.
title
title:alternative
title:part name
title:part number
title:subtitle

I'm coloring changes in yellow in object_import_template.

**Comment by lsitu** [comment]
@GregReser I think we need a way to interpret the Property names in dams4.2 data dictionary for coding/implementation. If the introducing of ":" is just for more readability purpose, can we just say that the right most part of the values in the property column is that we can use for UI display by default? If that works, we'll use that part as property name in our codes, which will show up on the UI as label by default. But it need to be unique across the data dictionary.

**Comment by ghost** [comment]
@lsitu Yes, as a starting point, the right most part of the values in the property column is that we can use for UI display by default.

"it need to be unique across the data dictionary" - so we can't have cases like this, right?
date:event
identifier:event

**Comment by lsitu** [comment]
Yes. Maybe we can do "date:date event" and "identifier:event id" in this case?

**Comment by ghost** [comment]
I see two conflicts, event and news release.

Let's change these:
identifier:event number
identifier:news release number

**Comment by lsitu** [comment]
Thanks @GregReser. I've created [PR#65](https://github.com/ucsdlib/horton/issues/65) to implement the identifier support. I think we can circle back with the implementation of the naming changes for other properties later when necessary.

**Comment by ghost** [comment]
@lsitu Excellent, thanks for working through the issues here.
