### ISSUE TITLE
Upgrade to latest Hyrax

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#64]
### Descriptive summary

Many commits have been introduced in Hyrax over the last few weeks.

Please:

- update our application to point to the latest.
- Confirm all tests still pass
- If any errors arise that seem to be upstream issues with Hyrax, please reach out and create issues in the Hyrax repository as needed.

### Rationale

In order to not fall significantly behind on the pace of change with Hyrax, we need to be vigilant about keeping up-to-date with the latest changes.

**Comment by mcritchlow** [comment]
@lsitu I heard that [Hyrax 1.0](https://github.com/projecthydra-labs/hyrax/milestone/6) may be released by the end of this week. 

Perhaps it may be best to hold off on this until next week?

**Comment by lsitu** [comment]
@mcritchlow I'll wait for it to upgrade horton then. Thanks.

**Comment by mcritchlow** [comment]
@lsitu - I spoke with Mike, and it sounds like we may be better off sticking with `master` for now re: hyrax. The 1.0 branch isn't really getting a lot of work done on it at the moment, and we won't get any new features there, perhaps just the occasional bug fixes So I think we'll need to stick with `master` for a little while longer.

**Comment by lsitu** [comment]
@mcritchlow Okay. I'll upgrade it once PR https://github.com/ucsdlib/horton/pull/76 get resolve, and I will balance my local work for batch ingest support for complex objects along with the Excel import template support to see whether we should hold off the upgrade to avoid the conflicts. Does it work with your plan? If not, I can do it now and fix the conflicts later.

**Comment by mcritchlow** [comment]
@lsitu - sounds good to me.
