### ISSUE TITLE
Audit Hyrax <-> D5 use of dc terms vs. dc11 properties 

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/horton#69]
### Descriptive summary

We have noticed in documentation and [Hyrax's basic_metadata code](https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb) some differences between Hyrax and D5 in the properties/namespaces for Dublin Core (`dc` vs. `dc11`). 

Note: to avoid confusion, since the syntax of the code is based on [rdf.rb](https://github.com/ruby-rdf/rdf), the prefix `dc:` _always_ refers to [DC Terms](http://dublincore.org/documents/2012/06/14/dcmi-terms/), while `dc11:` obviously refers to the [1.1 Elements](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#H3) namespace. 

A example of where Hyrax and D5 differ are Hyrax using `dc:rights` vs. D5 using `dc11:rights`. Should we find and reconcile the rest? 

### Rationale

Although we are obviously forking/extending the existing basic Hyrax metadata, if there is an opportunity for us to align with the Hydra/Hyrax community on shared properties/namespaces and still meet our local needs, it would be worth pursuing.

**Comment by lsitu** [comment]
@remerjohnson Attached is the Excel file with the difference in red for the terms and predicates used in [Hyrax basic metadata](https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb) and D5. It seems like some mapping are not clear enough (see my comments in the Notes):
[hyrax-d5_predicates.xlsx](https://github.com/ucsdlib/horton/files/891167/hyrax-d5_predicates.xlsx)

**Comment by remerjohnson** [comment]
@lsitu I put your sheet as a new sheet in the 4.2 data dictionary to discuss with DOMM. 

@GregReser then took the alignment and updated the properties in the main sheets and template. The changed properties are highlighted in yellow in the Google Sheet.

Two outstanding issues: 
* Since Hyrax is reserving `dc:created` for system dates of object creation, we can either "collapse" our idea of resource date creation into just `dc:date`, OR simply use a different predicate, such as `bf:originDate` ([link](http://id.loc.gov/ontologies/bibframe.html#p_originDate)). @ucsdlib/domm Thoughts? I'm trying to get more info about how Hyrax will likely handle descriptive metadata for dates, but haven't found anything. 
* Related resouce. Hyrax is using `rdfs:seeAlso`, but only expecting a simple URL. Can this be mapped to our current plan for the `schema:url` property within our class? See #58

**Comment by lsitu** [comment]
@remerjohnson For dc:created, I think we can still use predicate dc:created but just use another property name, such as [created_date](https://github.com/ucsdlib/horton/blob/develop/app/schemas/local_authority_schema.rb#L39) as currently used in horton. This could avoid the conflicting of the time valve that Hyrax used by default for system dates and the TimeSpan class that we are using.

**Comment by remerjohnson** [comment]
@lsitu We could do that, but then it would raise the question of when would we ever use just `dc11:date`? Is there a way we can assert on the ontology level that all of our date types are `sameAs` `dc11:date`?

**Comment by lsitu** [comment]
@remerjohnson Good question! Are you going to use dc11:date for all date types?

**Comment by remerjohnson** [comment]
@lsitu So I asked Mike Giarlo about this `dc:created` situation, and he said that he believes [date_created](https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L24) _is_ descriptive metadata, and _not_ reserved for Hyrax system uses.  

He believes those system dates come from the [core_metadata file](https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/core_metadata.rb#L25-L33). 

So it seems we have no conflict. Our `date:created` seems to now map cleanly to [Hyrax](https://github.com/projecthydra-labs/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L24)

**Comment by lsitu** [comment]
That sounds good and we can use dc:created. Thanks @remerjohnson. However, I do see some unexpected result in the past when I use it and I noticed that property name date_created is referenced every where over hydra/hyrax. For example, https://github.com/projecthydra/hydra-works/blob/master/lib/hydra/works/characterization/schema/base_schema.rb#L7 .

**Comment by remerjohnson** [comment]
@lsitu True, I've seen that before. I'm assuming that's the PCDM:File class? 

I think this is heading into unsettled territory, and hoping the metadata folks in the community can maybe help out here. We could change our property name to avoid conflicts. At least in the example you have, it points to ebucore and not dc. But yes, still sub-optimal.

**Comment by lsitu** [comment]
@remerjohnson Yes, I think it's used in the PCDM:File, and hyrax expected date_created to be a 'date string', which is conflicting with our TimeSpan as well. For example, https://github.com/projecthydra-labs/hyrax/blob/master/app/helpers/hyrax/citations_behaviors/publication_behavior.rb#L6-L11.

**Comment by remerjohnson** [comment]
@lsitu I see. Our dates here will be strings, we just wanted the range to be our TimeSpan class, so it would start with a string in the `prefLabel`. Is it that the code just won't parse it?

**Comment by lsitu** [comment]
@remerjohnson I think when referenced by object, it'll be a TimeSpan. When using the values in solr, then it depends on how we index those values. But both label and the hash/json value should be there.

**Comment by lsitu** [comment]
@remerjohnson Good news is that Hyrax is trying to separate the basic metadata that could be used/referenced internally with the descriptive metadata from the object/collection models. I see the BasicMetadataIndexer class is extracted that can added to or removed from the object/collection model, which making it a good step toward it.
I think the conflicting issue with the property name like date_created for TimeSpan could be fully resolved once we upgrade to the latest Hyrax 2.0.alpha on github.

**Comment by remerjohnson** [comment]
@lsitu Yes, that's good. It seems both devs and metadata people are moving along, so this a fluid situation. 

I now see there is no references to just `dc:date` anywhere for Hyrax. Should we still support it for description at all?

**Comment by lsitu** [comment]
Yes. we can support it in any way you want. I think we can ignore those basic descriptive metadata defined in Hyrax and build our own data model.

**Comment by lsitu** [comment]
@remerjohnson We just talked about the ticket during our sprint wrap up meeting. Is there anything else you want me to do? Otherwise I think we can close the ticket.
