### ISSUE TITLE
Confirm breadcrumbs support

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#70]
### Descriptive summary

It appears that Hyrax bundles in some support for breadcrumbs via [`render_breadcrumbs`](https://github.com/projecthydra-labs/hyrax/search?utf8=%E2%9C%93&q=render_breadcrumbs&type=)

[A more complete listing of breadcrumbs in Hyrax](https://github.com/projecthydra-labs/hyrax/search?utf8=%E2%9C%93&q=Breadcrumbs&type=)

Please:

1. Look into what this feature provides natively
2. Post screenshots demonstrating the scope of what "breadcrumbs" means in this context

### Rationale

"Breadcrumbs" are a desired feature to bring into the new system that was not re-created in DAMS4.

**Comment by hweng** [comment]
@mcritchlow 
The hyrax project use gem breadcrumbs_on_rails, 
https://github.com/projecthydra-labs/hyrax/blob/1e504c200fd9c39120f514ac33cd42cd843de9fa/app/builders/hyrax/bootstrap_breadcrumbs_builder.rb

which in your controller, call add_breadcrumb to push a new element on the breadcrumb stack. add_breadcrumb requires two arguments: the name of the breadcrumb and the target path.
There is a class breadcrumbs.rb created in hyrax to handle it:
https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/breadcrumbs.rb#L5

Currently the default_trail is like this, the label name is read from config/locales:
https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/breadcrumbs.rb#L14

And there is breadcrumbs_for_collections.rb to define default collection breadcrumb behavior, and breadcrumbs_for_works.rb to define default object breadcrumb behavior:
https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/breadcrumbs_for_collections.rb
https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/breadcrumbs_for_works.rb

Attached screenshots show the default breadcrumbs behaviors for collection and objects.

**Comment by hweng** [comment]
After log in, the object and collection view breadcrumbs:
![my_work](https://cloud.githubusercontent.com/assets/2432753/24819668/68a52f10-1b9a-11e7-8341-a9dd4980ed6b.png)
![my_collection](https://cloud.githubusercontent.com/assets/2432753/24819670/6c87cf70-1b9a-11e7-9adf-8439712c052b.png)

**Comment by hweng** [comment]
After log in, the collection and object edit action breadcrumb:
![my_work_edit](https://cloud.githubusercontent.com/assets/2432753/24819754/ca8a5656-1b9a-11e7-86e2-b57803b09649.png)
![my_collection_edit](https://cloud.githubusercontent.com/assets/2432753/24819756/cdadc2dc-1b9a-11e7-9cce-7e4f92310cdb.png)

**Comment by hweng** [comment]
The public view for collection and object breadcrumb:
![public_view_collection](https://cloud.githubusercontent.com/assets/2432753/24819778/e8e1b7f2-1b9a-11e7-826c-c561a870224a.png)

![public_view_work](https://cloud.githubusercontent.com/assets/2432753/24819783/eac584ae-1b9a-11e7-8e48-502f14a5bdf2.png)

**Comment by mcritchlow** [comment]
@hweng - thanks for posting these. If a user is not authenticated, will they see any breadcrumbs? Or are these breadcrumbs only shown for authenticated users and specific to their content?

I suspect all we'd want is essentially (at the object level) breadcrumbs that say:

`Animal Collection / Bunny 1`, for example.

**Comment by hweng** [comment]
@mcritchlow If a user is not authenticated, they can still see the breadcrumb, but the trail is different from the logged in user, see the above public viewer vs. logged in viewer screenshots:
For example:
Logged in: My Dashboard/My Objects/ Bunny
Not logged in:  My Objects/Bunny

For your 2nd question: No, the current hyrax behavior for object breadcrumb is that it doesn't include collection name in the trail:
For example:
The Bunny object which belongs to the Animal collection, it's trails is:
My Dashboard/My Objects/ Bunny

And the animal collection trail is:
My Dashboard/My Collections/Animal Collection

https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/concerns/hyrax/breadcrumbs_for_works.rb#L26

**Comment by mcritchlow** [comment]
@hweng - I see, thanks for clarifying. Based on what you've learned so far, do you think it would be difficult to adjust/override so that, for example, the Object includes a breadcrumb back to the Collection? 

And, to clarify, I think everything you've already provided covers the scope of this ticket. Any actual customization can be done in a new ticket, if we decide to go that route.

**Comment by hweng** [comment]
@mcritchlow I think it is possible to override the hyrax breadcrumbs behavior to link back to the collection, but i'm not sure how difficult it is. I will look into it and figure out if we decide to go that route.

**Comment by mcritchlow** [comment]
@hweng - Sounds like a plan. I think you can mark this Closed for now then, and we can chat with @gamontoya about when/if we may want to do any modifications via a separate ticket.

**Comment by gamontoya** [comment]
@mcritchlow I think we want to see if the modifications (to pull in the collection) can be done and creating a new ticket sounds perfect.

**Comment by mcritchlow** [comment]
@gamontoya sounds great, it's created as #83
