### ISSUE TITLE
Upgrade Nokogiri

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#75]
### Descriptive summary

Address security vulnerability:

https://gemnasium.com/github.com/ucsdlib/horton

**Comment by lsitu** [comment]
Hi Matt,
It looks like we have no risk for Horton at this time yet. Could I work on it later after I wrap up my works at hand so that it won't mess it up?

**Comment by mcritchlow** [comment]
@lsitu Yes, definitely. You're correct it's not a big deal for horton since it's not actually deployed anywhere.

**Comment by lsitu** [comment]
I've done it for damspas. But we have to wait for the slow ci/circleci build, which could take more than two hours.
