### ISSUE TITLE
Batch Import Support Update

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#81]
### Descriptive summary

This ticket primarily addressed a number of issues outlined by @GregReser in his [comment](https://github.com/ucsdlib/horton/issues/46#issuecomment-291241448) via #46 

Summarized again here:

- Initial support for complex objects
- resolve relatedResource predicate(s) and Class #58
- resolve rights properties
        do we need copyright status or can it be inferred from rights URI?
- resolve Matt's question about identifier:roger record (should it be more generic, e.g., "identifier:catalog_record"
- add remaining agent predicates (it's a long list and I was waiting because it will make the template harder to read).

@lsitu In the object_import_template, I've been highlighting changes in yellow to make sure they you see them. I suggest you remove the yellow when you have implemented the change. This way we will all know what remains to be updated.

### Related work

#46

**Comment by ghost** [comment]
@lsitu We are thinking of adding a column to the ingest template for file path.
Why?
1. Source files can have duplicate filenames in sub-directories which can result in the wrong file being linked to an object.
2. File directory structures can be very large and complex with many non-ingested files.  Specifying the path might speed up file match - maybe?

However, it is convenient to specify the path in the ingest form when there are no filename or directory complications.  

Could we have both options: specify the path in the form (as we currently do) or enter the path in the spreadsheet?  The spreadsheet path would override the form path. Is that possible?  Is it a good idea?

**Comment by lsitu** [comment]
@GregReser Horton/Hyrax will allow us to select the specific files/directories from the remote server  for ingest and/or upload files from local disk as well. So the duplicate filenames issue could be avoided at ingest. And I think we may want to keep this feature in the UI for batch ingest.
However, I think we can also add a column for the file path in the spreadsheet. In this case, we consider that the file is located at the server side location "#{file path}/#{file name}", which override the files uploaded to the server as you suggested and the files uploaded will be ignored at the mean time. Does it what you want?

**Comment by ghost** [comment]
@lsitu Yes, I think we are are the same track.  Here's another way to say what I mean:

The UI batch ingest would allow you to specify the directory for files in a batch.
The spreadsheet would have two columns: file path and file name.  We want them separate for human readability.
For each row in the spreadsheet, 
- if file path column is blank, the path in the UI is used
- if file path column has a value, the path in the spreadsheet is used.

Complications:
- What if UI file path is not specified? Pre-ingest validation should catch this (UI path is not required, but if it's not specified, then every spreadsheet row must have a path)
- What if the spreadsheet path is invalid? Pre-ingest validation should catch this.  Testing each path might be slow.

**Comment by lsitu** [comment]
@GregReser It sounds good. Do we still need the file path for the second file for "file 2 name"?
How about discuss and implement the validation function later in another ticket so that we can move this ticket forward?

**Comment by ghost** [comment]
@lsitu I think file 2 name should always use the same path as File 1 name.  Yes, we can work out the validation later.

Unless anyone else sees a problem, I will add a file path column to the D5 template.
