### ISSUE TITLE
Implement Breadcrumbs for Collection/Object hierarchy

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#83]
### Descriptive summary

 As noted in #70 there is already breadcrumb support built in for Hyrax, however it is targeted more towards "The things that I have ingested" as opposed to the actual hierarchy of the collections and objects themselves.

### Rationale

This is a feature that is desired by the DLDP is to have objects include their parent collection in a breadcrumb interface. If possible, we should implement it to satisfy that feature requirement.

### Expected behavior

When viewing an object that is part of a Collection (say "Collection A") then breadcrumbs should appear on the object view page demonstrating this relationship.

### Actual behavior

The current behavior is nicely demonstrated via screenshots from @hweng in #70 

### Related work

#70

**Comment by hweng** [comment]
@mcritchlow Should the collection/object relationship show in the breadcrumb trail when the object request is referred from outside website?  For example, from other website click the link and be directed to our object_resource page.

**Comment by mcritchlow** [comment]
Great question, we should have clarified that in the Description originally.

We don't want the breadcrumbs to be based on navigation/history, but instead they should be 'static' in the sense that the object page should always have a breadcrumb link back to its collection.

So to your question more directly, yes if someone came in from a Google search and landed on an object, it should show a breadcrumb link to the object's collection record.

**Comment by hweng** [comment]
Ok , We will always keep the Collection/Object hierarchy. For other trails, do we want it to be partial static or complete static? The partial static means display some history, For example, if user logged in it would display the trail "My Dashboard/", otherwise it is not,  and if in edit, it display "edit", and etc.

**Comment by mcritchlow** [comment]
Yeah, also a good question.

I think those other, existing breadcrumbs we'll probably need someone to evaluate and get us more feedback. That might end up being part of the larger UI/UX evaluation an design phase we'll have later in the project. For now, assuming it doesn't conflict with adding these static Collection/Object breadcrumbs on the show pages, I think we can safely leave the other breadcrumbs as-is.

**Comment by hweng** [comment]
Get the modified breadcrumb behavior working.  @mcritchlow, please take a look of the following screenshots with different trail, and let me know if it looks good to you:

In public view(non-logged in):
<img width="945" alt="screen shot 2017-04-28 at 9 59 48 am" src="https://cloud.githubusercontent.com/assets/2432753/25544534/c0afe3e6-2c0f-11e7-82ea-7be2e0f78c27.png">

In logged in view:
<img width="943" alt="screen shot 2017-04-28 at 9 58 51 am" src="https://cloud.githubusercontent.com/assets/2432753/25544493/8fe3efdc-2c0f-11e7-9304-ca311c1c8b4f.png">

In edit view:
<img width="1068" alt="screen shot 2017-04-28 at 10 00 55 am" src="https://cloud.githubusercontent.com/assets/2432753/25544463/6d3faac0-2c0f-11e7-9d4c-cbc9934517fc.png">

**Comment by mcritchlow** [comment]
That looks great @hweng, nice!
