### ISSUE TITLE
Implement new Rights metadata model

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#84]
### Descriptive summary

While it was designed to simplify rights and access controls, the new rights management strategy and metadata model is significantly different then what we implemented in 4.

Need a full spec including:
- list of properties
- associated application behavior (verified with the library rights policy group)
- controlled value lists or validation rules for each property
- properties and validation rules for entry via the CSV ingest stream
- wireframe for entry via the MARC/AT ingest stream

Central to this, and a prerequisite before finalization of spec:

- analysis of existing Hyrax access controls (dev ticket?)
- depending on implementation the access controls related to QA and release to final access state (public, ucsd only, etc.)

### Related Work

#46

**Comment by mcritchlow** [comment]
Noting Longshou's previous work in providing examples of the various Hyrax access control states:

https://github.com/ucsdlib/dams5-cc-pilot/issues/40#issuecomment-261614672

**Comment by lsitu** [comment]
@ucsdlib/domm Looking into the Hyrax implementation for visibility with embargo and lease, it uses predicates like acl:hasEmbargo and acl:hasLease to mark those two special states to trigger it for object access and UI display. Could we implement it the similar way for out local visibility like suppress discovery, metadata only, and culturally sensitive?
I think we can either use the existing pcdmrts:rightsOverride predicate with url value (just like what is suggested in the data dictionary: http://library.ucsd.edu/ontology/dams5.0access#culturallySensitive, http://library.ucsd.edu/ontology/dams5.0access#metadataOnly and http://library.ucsd.edu/ontology/dams5.0access#suppressDiscovery), or use different predicates with more complex structure/value for each case. We'll implement it by setting the public permission internally in combining it with the rightsOverride predicate/value to trigger the expected behavior we want for object/file access control and UI display.
What do your suggest for implementation? Thanks.

**Comment by mcritchlow** [comment]
@ucsdlib/domm - Is there any additional information that @lsitu can provide to help with this? Do we need another mtg? Just curious what the best way would be to make progress on this.

**Comment by ghost** [comment]
I need more information before I can add useful comments.  Where is the documentation for how Hyrax is using acl?  I found this, but it doesn't cover embargo or lease: https://anarchivist.gitbooks.io/hyku-models/models/permissions.html 

When I look at general acl documentation, I get a little scared by their use of agent and group for permissions.  Is that where we would be going?

**Comment by lsitu** [comment]
@GregReser I think this model is introduced in the hyku project, which should be built on top of hyrax and I don't know whether it's implemented or not. And @mcritchlow may know more about it. But we've implemented  our own group access control basing on hyrax, which is similar to what we've done for DAMS4. 

Here is the hydra local defined acl terms: https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/vocabularies/hydra/acl.rb.

**Comment by lsitu** [comment]
@GregReser Here is an overview of hydra access control that you may be interested in: https://github.com/projecthydra/hydra-head/wiki/Lesson---Quick-Overview-of-Access-Controls-in-Hydra

**Comment by ghost** [comment]
It looks like using hydra access control would add some complexity - more properties.  Am I right in saying they don't have a simple visibility property, they have 4?
acl:visibilityDuringEmbargo
acl:visibilityAfterEmbargo
acl:visibilityDuringLease
acl:visibilityAfterLease

We aren't using lease, so we can eliminate that, but we would still have two.  Is that right?
acl:visibilityDuringEmbargo
acl:visibilityAfterEmbargo

**Comment by lsitu** [comment]
@greg Yes, they use two visibility properties for embargoed objects. The first one acl:visibilityDuringEmbargo is private by default while the other (acl:visibilityAfterEmbargo) is public. Do we need to change the behavior of the embargoed objects implemented in hyrax as well?

**Comment by ghost** [comment]
@lsitu We were not going to use a property like visibilityAfterEmbargo.  Instead, visibility would always change to "public" when the embargo expires.

We currently handle embargo with two properties:
embargo expiration
visibility

Hydra would be at least 4 properties:
hasEmbargo
visibilityDuringEmbargo
visibilityAfterEmbargo
embargoReleaseDate

From a policy point of view, I don't think we need additional properties to drive visibility.   If we change to using hydra access control properties, will implementation be easier?  Is there a reason to do it from the coding point of view?

**Comment by lsitu** [comment]
@GregReser Actually the term `visibility` in hyrax is not a property but a keyword/variable that is keeping track of the state of an object.
I think it'll be great if we can utilize the terms in hyrax and map our properties to it. If we can't do that, we'll see how to implement our version of it. But I would suggest following the implementation pattern in hyrax for visibility to have a predicate like acl:hasEmbargo, or using the value of a predicate like pcdmrts:rightsOverride,  to mark the embargoed objects. If we implement our own version, we'll lost any functionalities implemented in hyrax for accessing the embargoed objects during the embargoed period and after embargo expiration, as well as the function to release the embargoed objects.

**Comment by ghost** [comment]
@lsitu losing hyrax embargo functionalities is a very good reason to change to the acl properties.  If we do this, can we just implement these properties for embargo (not do lease at this time)?
acl:hasEmbargo
acl:visibilityDuringEmbargo
acl:visibilityAfterEmbargo
acl:embargoReleaseDate

These would replace our embargo expiration (row 69)  and visibility (row 70) in "dams5_data_dictionary", correct?

Is there a CV for visibilityDuringEmbargo and  visibilityAfterEmbargo? is it the same one we use now? [public, private, metadata only, discovery suppressed]

**Comment by lsitu** [comment]
@GregReser Yes for the properties. But we just need to provide the values for acl:visibilityDuringEmbargo, acl:visibilityAfterEmbargo and acl:embargoReleaseDate and hyrax will construct an Hydra::AccessControls::Embargo instance for property acl:hasEmbargo.

Yes, These would replace our embargo expiration (row 69) and visibility (row 70) in "dams5_data_dictionary".

At this time, I think the CVs for visibilityDuringEmbargo are [private | campus], while the CVs for visibilityAfterEmbargo is [public|campus]. If we need other CVs, like metadata only, discovery suppressed etc, we'll see how to make it works.

**Comment by lsitu** [comment]
@GregReser I think we may still need a way to mark a state of and object. Is column visibility a good fit for values like public, campus, curator, suppress-discovery, metadata-only, and culturally-sensitive? I think we can assume that the state of an object (visibility) is implied by the combination of permission (such as public, campus etc) and predicates like acl:hasEmbargo, pcdmrts:rightsOverride etc. This will have Hyrax to build a Hydra::AccessControl instance and a Hydra::AccessControls::Permission instance for object access controls.

**Comment by ghost** [comment]
@remerjohnson what do you think?

**Comment by remerjohnson** [comment]
I think it could work. It's a little unwieldy at the spreadsheet level, but it seems like this wouldn't be used so often, and would help when you have a collection with many different embargo dates (as some of our research collections do).

**Comment by ghost** [comment]
OK, trying to translate this into "dams5_data_dictionary".  I've updated it with these properties.
69 - embargo release date
70 - visibility during embargo
71 - visibility after embargo
@lsitu when you say "we may still need a way to mark a state of and object", do you mean we need another property to record for values like public, campus, curator, suppress-discovery, metadata-only, and culturally-sensitive?

**Comment by lsitu** [comment]
Thanks Greg.
Yes, we need a way to address the visibility/state of the object which is used by Hyrax to build  permissions for access control. This is the visibility option in the object ingest form https://github.com/ucsdlib/horton/issues/85#issuecomment-295342365. However it's not a property but a variable/keyword in hyrax that is used to create the permissions for access control. The predicate is [w3 acl:accessControl](http://www.w3.org/ns/auth/acl#accessControl) and the class Hydra::AccessControl, which holds permissions (Hydra::AccessControls::Permission class instances). This is canned by Hyrax something like a black box for us. I don't know whether you would like to go through all those codes or not but here is the project for the implementation: https://github.com/projecthydra/hydra-head/tree/master/hydra-access-controls.

**Comment by ghost** [comment]
Will the ingest form also have visibility settings for after embargo?  Can we just make it always "public" (no selection necessary by the user)

**Comment by lsitu** [comment]
Yes. The form has visibility settings for after embargo. And we can make it always "public".

**Comment by ghost** [comment]
OK, then for the object_import_template, we only need one column for visibility and for clarity (so we know what it is for), let's call it "visibility during embargo".  Will that work?

**Comment by lsitu** [comment]
Hi Greg,
Yes. That works! Thanks. We can simply set visibility_after_embargo to public/open access when object is embargoed.
How are we going to address the visibility state in the [dams5 data dictionary](https://docs.google.com/spreadsheets/d/134Hxqafmz70X0glD3T98-pLMUwOK18oftvdSWOYdJ2k/edit#gid=616154196)? And how about the predicate(s) for our custom visibilities (suppress-discovery, metadata-only, and culturally-sensitive)?

**Comment by ghost** [comment]
I guess we can't extend the CV for visibilityDuringEmbargo [private | campus], right?

**Comment by lsitu** [comment]
Yep, I think it could be a little tricky since this will bring up lots of things from the bottom of hyrax.

**Comment by ghost** [comment]
Does hyrax have a simple visibility setting (not during or after embargo, just simple visibility without any embargo applied)?

**Comment by lsitu** [comment]
No. It's a fixed model but I think we can simply set visibility_during_embargo to private/curator, just like what we've discussed for visibility_after_embargo.

**Comment by remerjohnson** [comment]
@lsitu re: https://github.com/ucsdlib/horton/issues/84#issuecomment-299560522 

We have those as access/override predicates still in the data dictionary "Rights/URI's" tab. Are these still doable?

**Comment by lsitu** [comment]
Yes, it sounds good and I can start with the implementation once we agree on that.

**Comment by ghost** [comment]
Which predicates from "Rights/URI's" tab?
pcdmrts:rightsOverride
pcdmrts:rightsOverrideExpiration

**Comment by lsitu** [comment]
@GregReser I am fine with pcdmrts:rightsOverride. But will we still use pcdmrts:rightsOverrideExpiration with embargo settled by acl:embargoReleaseDate?

**Comment by ghost** [comment]
I don't think so, but that's what I was unclear about.  Would we use pcdmrts:rightsOverride when there is no embargo or is anything not "public" embargoed?

I added visibility on row 69 of [dams5 data dictionary ](https://docs.google.com/spreadsheets/d/134Hxqafmz70X0glD3T98-pLMUwOK18oftvdSWOYdJ2k/edit#gid=616154196)
Is the CV OK? [suppress-discovery | metadata-only | culturally-sensitive]

What else do we need for this?

**Comment by lsitu** [comment]
I think this is good enough for the implementation. Just a little question that I can't use the hyrax keyword `visibility` as the property name for pcdmrts:rightsOverride. Could we use `rights override` as the property name instead?
Also, in the [object import template](https://docs.google.com/spreadsheets/d/1EhMWaDFsBZDhp-BU-5LtOI0tECDx2EtAZ28iZk-Ih58/edit#gid=559462679), do you still want a visibility column with the CVs from the [visibility options menu](https://github.com/ucsdlib/horton/issues/85#issuecomment-295342365)? As we discussed in the past, this will override the visibility selected from Batch Import Form when a value appear for an object record. What do you think?

**Comment by lsitu** [comment]
@GregReser I see the Range (xsd:anyURI) and the instructions for visibility_during_embargo in the [Object Import Template](https://docs.google.com/spreadsheets/d/1EhMWaDFsBZDhp-BU-5LtOI0tECDx2EtAZ28iZk-Ih58/edit#gid=559462679) (row # 125) doesn't inline with what's in Hyrax, which are literal values (open for public and authenticated for campus/institution). I think we have no control over these visibility values in Hyrax but we can simply convert it to the values that Hyrax expected if we want to use our own expression. Do you have any concerns regarding it?

**Comment by ghost** [comment]
@lsitu I updated visibility_during_embargo to rdfs:Literal	string (controlled [private | campus])
I guess we will also need an import header for the visibility value we are using in pcdmrts:rightsOverride

**Comment by lsitu** [comment]
Thanks Greg. I'll implement the visibility header as an option to override the value submitted from the Batch Import form then. Is it Okay to use rightsOverride as the properties name for predicate pcdmrts:rightsOverride (see row # 69 in [dams5 data dictionary](https://docs.google.com/spreadsheets/d/134Hxqafmz70X0glD3T98-pLMUwOK18oftvdSWOYdJ2k/edit#gid=616154196))?

**Comment by ghost** [comment]
Yes, but let's make pcdmrts:rightsOverride  properties name "rights override", following or convention for other labels.

**Comment by lsitu** [comment]
@GregReser It sounds good and I'll use "rights override" as property name. 
I also found that the CVs for column `copyright status` may not be inline with those in the dams5 data dictionary and the [rights metadata documentation](https://lisn.ucsd.edu/display/DOMM/Revised+Rights+Metadata+Structure+Recommendation+2017). Could you take a look?

**Comment by lsitu** [comment]
Also, do we still have [rights statement](https://docs.google.com/spreadsheets/d/1EhMWaDFsBZDhp-BU-5LtOI0tECDx2EtAZ28iZk-Ih58/edit#gid=559462679) (row#122)? I don't see it in the dams5 data dictionary.

**Comment by lsitu** [comment]
@GregReser It looks like that the CVs for license (row#124) in the [object_import_template](https://docs.google.com/spreadsheets/d/1EhMWaDFsBZDhp-BU-5LtOI0tECDx2EtAZ28iZk-Ih58/edit#gid=559462679) is outdated as well. The CVs still under header `rights|rights MATCH` and some values are different from the dams5 data dictionary. Could you take a look as well?

**Comment by ghost** [comment]
@remerjohnson which URIs are we using for copyright status?  On dams5_data_dictionary, the values given in Rights URIs and Controlled Values tabs are different.

**Comment by ghost** [comment]
@remerjohnson confirmin that the rights properties in dams5_data_dictionary are up to date.  
We are no longer using rights statement
copyright status is now using the predicate edm:rights and the CV is ?

**Comment by ghost** [comment]
@lsitu I have update the object_import_template license CV to match dams5_data_dictionary

**Comment by lsitu** [comment]
Thanks, Greg. I'll update the object_import_template for horton then.
