### ISSUE TITLE
Mockup new Visibility form

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#85]
### Descriptive summary

@ucsdlib/domm could use a mockup/screenshot for what the visibility part of the form would look like when the new visibility values and descriptions are added in. This would be purely a web mockup, not an actual implementation, which is slated for #84 

The mockup should include the following:

1. Add new visibility options below the defaults: Suppress Discovery, Metadata Only, Culturally Sensitive
2. Add boilerplate helper text for each option. May need help from @ucsdlib/domm on this one.
3. ..?

### Rationale

It would be helpful to have a visual when discussing rights, access control, license, etc.. It will also help ensure we are only adding to the existing Rights/Access Control/Visibility design and behavior provided by Hydra.

### Related work

Documentation:
* https://lisn.ucsd.edu/display/DOMM/Revised+Rights+Metadata+Structure+Recommendation+2017
* https://docs.google.com/spreadsheets/d/134Hxqafmz70X0glD3T98-pLMUwOK18oftvdSWOYdJ2k/edit#gid=616154196

#84

**Comment by lsitu** [comment]
@ucsdlib/domm What boilerplate helper text would you like for Suppress Discovery, Metadata Only, and Culturally Sensitive in item#2 under "Descriptive summary"?

**Comment by lsitu** [comment]
@ucsdlib/domm I've moved ahead to mockup the visibility form and we can change the  boilerplate helper text later at any time. Here are the screenshots:

- Visibility component
<img width="396" alt="screen shot - visibility options" src="https://cloud.githubusercontent.com/assets/2430784/25191704/536bd4f6-24e5-11e7-9590-dfc34fcd542a.png">

- Batch Import Form
<img width="1437" alt="screen shot - batch import" src="https://cloud.githubusercontent.com/assets/2430784/25191832/b7a9b3b6-24e5-11e7-9f2d-4a643e7178c7.png">

- Object Edit Form
<img width="1440" alt="screen shot - edit form" src="https://cloud.githubusercontent.com/assets/2430784/25191846/c6fa23aa-24e5-11e7-9218-6534b062103f.png">

**Comment by arwenhutt** [comment]
@lsitu 
This is helpful, thanks!
A rough pass at the description text:
- Suppress Discovery - exclude from searching and discovery but accessible via direct link
- Metadata Only - metadata record is available but files are suppressed
- Culturally Sensitive - files available after click through to indicate that materials may be of a sensitive nature

@ucsdlib/domm @mcritchlow @lsitu Seeing this mock up raised a few other questions for me though on how the default Hyrax access states line up with ours.
- Open Access - Maybe it's just the description text but this seems to be presented as being a little different then "public"
- Private - We had mapped this to our "curator only" state but from the description text it looks like it is a different kind of access state.  A few possibilities for dealing with this:

1. We could limit the "users and groups that have been given specific access" to curators in the functionality to make it essentially the same as our curator only status.
2. If we are looking at possibly having more granular user permissions/access controls in the future (I'm thinking about the virtual reading room use case), then we could keep the Hyrax "private" option, and add an additional "curator only" option for our current use case. 
3. We could change "embargo" to not require an end date and use that for curator only materials

Looking at it right now, I'd lean toward 2 but would like to hear what others think.

**Comment by remerjohnson** [comment]
It's clear the legacy of that form was trying to get users (non-admin) to get their heads around the access states, so in that sense "Open Access" is a more known term implications-wise than "Public." If the end result access state is the same, I don't really see a problem with adopting either terminology.   

Honestly the most "right"-sounding option is 3, since as CDL recently noted, keeping data private until ready to show is really stretching the notion of an "embargo" and this notion could extend to really any object/collection we want to keep data private, expiration date or no. 

However, I do also lean toward 2 just because of that looming "virtual reading room" issue and the general request (which I dislike, but what can you do?) of having a lot of granular/per-collection/per-object permissions. And if that understanding of "User groups" and AdminSets and whatnot is built into Hyrax, we may as well go along with that mode of doing things. But, ugh, dealing with that mess in Islandora was a colossal headache and never seemed to be satisfactorily resolved (and then it was modeled out elegantly, yet never used).

**Comment by lsitu** [comment]
@arwenhutt I'll update the description text when implementing it in https://github.com/ucsdlib/horton/issues/84. Yes, "Open Access" is just the default description text in hyrax and it's equivalent to "Public" access. I think we can change it at any time.

FYI, the workflow will be introduced with the latest Hyrax 2.0.alpha on github master branch that can be used for some special needs. I see it's working with Horton when I working on ticket [Upgrade to latest Hyrax](https://github.com/ucsdlib/horton/issues/64). 
With the workflow feature, we can assign curators/curator group or viewers to an Admin Set, which allow curators to review and viewers to view those objects deposited into that admin set.
Here is the screenshots for a curator and a public user to access an object:
<img width="1438" alt="screen shot - curator review" src="https://cloud.githubusercontent.com/assets/2430784/25198406/4299c536-24fc-11e7-86ec-341422608dd9.png">
<img width="1440" alt="screen shot - pending review" src="https://cloud.githubusercontent.com/assets/2430784/25198405/42984f6c-24fc-11e7-8763-427e70284f61.png">

**Comment by lsitu** [comment]
@arwenhutt For the "Private" visibility, we've implemented the group access control and all curators (editor and curator roles) can view those private objects. So I think it's actually the "curator only" state as we need at this time. We may just need to update the description text, which is coming from Hyrax by default.

**Comment by lsitu** [comment]
@arwenhutt Is there anything else that you would expect me to do for this ticket? Otherwise I think we can close the ticket and move forward with https://github.com/ucsdlib/horton/issues/84 for implementation. What do you think?

**Comment by lsitu** [comment]
@ucsdlib/domm Here is additional mockup/screenshot for the the object list that a curator can see once the new visibility/rights model implemented:
<img width="1437" alt="screen shot - curator view" src="https://cloud.githubusercontent.com/assets/2430784/25585272/99045700-2e4e-11e7-8ad5-3a6a806554c0.png">

**Comment by lsitu** [comment]
@arwenhutt I think we've implemented the mockups in ticket [Implement new Rights metadata model](https://github.com/ucsdlib/horton/issues/84) (see PR https://github.com/ucsdlib/horton/pull/108). Could we close the ticket now? Thanks.

**Comment by mcritchlow** [comment]
@lsitu i think we'll close this out and open a new ticket if/when changes are needed. this is an excellent first pass.
