### ISSUE TITLE
Remove local pages implementation, replace with Hyrax default

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#89]
### Decision
per @gamontoya - We should try it out (Hyrax out of the box) at first and revisit.

Tasks:

- [ ] Remove local Pages implementation
- [ ] Create entries in the routes file for our existing static pages: about, faq, takedown, search-tips. Hang off the root, if possible, so the about page will be: `https://<application-path>/dc/about`, for example.

### Descriptive summary

Currently, out of the box, Hyrax provides a mechanism for defining new pages. This is how the About, Help, Contact, pages are defined. As well as specific sections on the default homepage. We could potentially choose to use this for our local pages needs, in place of the custom implementation we created.

I think we need input from @gamontoya and others on what we really need from these pages. For example, how often are end users going to really create "new" pages? Has that feature actually been helpful? It would seem that hasn't been used in damspas.

Note: Matt can give Gabriela a demo to show the UI/UX of each.

### Rationale

Pros for local implementation:

- Our pages implementation allow end users to create new pages without developer help
- Our pages implementation adds a WYSIWYG editor for managing content

Pros for Hyrax implementation:
- Already exists, and isn't something we need to maintain. Less code on our end means faster test suites, less technical overhead, etc.
- Very simple to add new pages, just a line in  `routes.rb`

### Related work

#53

**Comment by gamontoya** [comment]
@mcritchlow Where are we at with this ticket?

**Comment by mcritchlow** [comment]
@gamontoya we need to discuss still. maybe make part of our 1-1 agenda for next week?

**Comment by gamontoya** [comment]
## Background:

Sufia/Hyrax has its own static page feature that we can use.

## Pros and Cons:

- Pro: One less thing we would have to be responsible.
- Con: Doesn't have WYSIWYG editor into it. Would need to know what HTML to add.

We could ditch the pages things entirely and have them built out in the app as HTML pages but updates or changes would require a deploy.

## Decision:
**We should try it out (Hyrax out of the box) at first and revisit.**
