### ISSUE TITLE
R&D: Ordered Names

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#90]
### Descriptive summary

Identify options, if any, for supporting ordered field values in hyrax. Particularly, names.

### Rationale

We need to identify whether there is any support in hyrax for ordering names. We cannot do this in DAMS4, but we have an increasing number of examples in research data collections where name ordering is very important. 

### Expected behavior

A record contains links to four dc:creator's, we'll call them:

* Grad Student A
* Grad Student B
* Grad Student C
* Professor X

A curator would like to have a fixed name ordering so that in the object view (and search results if relevant) the names always show as below, ensuring Professor X is listed first:

* Professor X
* Grad Student A
* Grad Student B
* Grad Student C

### Actual behavior

Random. At the moment we have no control over this. Because all fields are stored in the graph for the object, and the graph itself has no concept of order.

**Comment by hjsyoo** [comment]
RDCP would also like control over display order in the following fields or values, in order of decreasing priority. The Names issue described above shares highest priority with the first item below:

1. Roles on landing pages. 
Example: In https://library.ucsd.edu/dc/collection/bb4473712z, ideal order of Roles is Leads, Director, Contributors, Research Team Members.
2. Objects in results view. 
Example: https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=California+Tobacco+Survey+%28CTS%29&id=bb9353145q. By default, collection items should display in title or date order within a collection. Sorting by order of relevance makes sense for all other searches, but not when Viewing Collection Items. In the CTS collection, the user wants to see objects in either date or title order. I'm not sure whether title or date should be the default order - this might need input from the larger group.
3. Related Resource links on landing pages. 
Example: https://library.ucsd.edu/dc/collection/bb9353145q. The list of external resources for CTS are in a more logical order on their former website, e.g., California Law and Federal Law are listed one after the other, and more peripheral documents are listed last. Also, disorientingly, the order of related resources can sometimes be ordered differently among similar but related objects.
4. Names in results view. 
Example: https://library.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Southern+Ocean+Carbon+and+Climate+Observations+and+Modeling+%28SOCCOM%29+Float+Data+Archive&id=bb4473712z. The lists of Names for each of the similar objects in this collection get re-randomized for each object, even though they were entered in the same, preferred order during ingest.

**Comment by lsitu** [comment]
@hjsyoo, @ucsdlib/domm Can the roles (Leads, Director, Contributors, Research Team Members etc.) that required ordering in # 1 above be mapped to the terms defined in the [dams5 data model](https://docs.google.com/spreadsheets/d/1OjTm1Kuzo-An-THdpUkjwa5puul-b4Lx3SK0lB6rvl8/edit#gid=616154196) or not?

Here are some terms from the [dams5 data model](https://docs.google.com/spreadsheets/d/1OjTm1Kuzo-An-THdpUkjwa5puul-b4Lx3SK0lB6rvl8/edit#gid=616154196) that could be related:
 - agent:contributor (dc11:contributor)
 - agent:researcher (MARCRelators:res)
 - agent:research team head (MARCRelators:rth)
 - agent:research team member (MARCRelators:rtm)
 - agent:principal investigator (ucsd:principalInvestigator)
 - agent:co-principal investigator (ucsd:coPrincipalInvestigator)
 - agent:laboratory assistant (ucsd:laboratoryAssistant)
 - agent:thesis advisor (MARCRelators:ths)
 - agent:creator (dc11:creator)

**Comment by hjsyoo** [comment]
@lsitu After conversing with mcritchlow, I think this ticket was meant to serve primarily as a request to investigate whether curators can have some control over ordering in DAMS5. If any of it can be implemented earlier or specifically for the SOCCOM collection, that'd be great.

**Comment by lsitu** [comment]
@hjsyoo I've posted a question, https://groups.google.com/forum/#!topic/hydra-tech/_7wzCLoeRmg, in the hydra community. Let's see what we can do.

**Comment by arwenhutt** [comment]
Ordering is definitely a weaknesses of RDF.  Right now imposing order involves adding layers of hierarchy (blank nodes) to the data structure which adds complexity to every bit of code that needs to interact with that data.  That's why we've only done this (locally and as a community) when it's absolutely required - as with ordering of components of a hierarchical object.  I think the functionality proposed in this ticket makes sense and is appealing, but I think that it would be hugely resource intensive to try and implement on our own, and it would also put us more out of step with the community development and reduce the chances we'd be able to reuse community built tools.  I would love to see a solution to this that was developed under the auspices of the larger community and Hyrax though.

**Comment by hjsyoo** [comment]
+1. Will keep fingers crossed that there's enough desire in the community to move in that direction, then!

**Comment by gamontoya** [comment]
@arwenhutt @mcritchlow Not to convolute but to clarify, should this not have been a feature request to have been vetted by the Products Group?

**Comment by mcritchlow** [comment]
@gamontoya - yes, i think so. while the scope was about R&D only in this ticket, that would have still probably been the correct route.
