### ISSUE TITLE
Port Metadata-Only feature

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#92]
### Descriptive summary

DAMS4 has a metadata only 'state' that is used for objects that we are allowed to make publicly available, but only the metadata, not any associated files.

If there is a newer/better means to accomplish this feature given the new Hyrax framework, let's discuss and implement that.

### Rationale

This is an existing DAMS access control feature that must be migrated.

### Expected behavior

Loading an object from the search results view, or via direct link, that has a metadataOnly value for rightsOverride (assuming agreement in #84 ), should only display the metadata for that object. No files should be visible or accessible from a public user.

Example in DAMS4: *needed for reference*

### Actual behavior

not implemented. At the moment the user would see the metadata and the files for the given object.

### Related work

#84 #85

**Comment by lsitu** [comment]
@mcritchlow Hyrax has the visibility_badge that marks an object's state/visibility, which is triggered by the the visibility implemented in https://github.com/ucsdlib/horton/issues/84. And the file download is more or less related to access control too. So it looks like the feature here is a little bit overwrap with ticket https://github.com/ucsdlib/horton/issues/84. But I think we can evaluate what else we still need to port once ticket https://github.com/ucsdlib/horton/issues/84 is done.
